#line 2 "Frontend/Parser/LexicFormula.cc"

#line 4 "Frontend/Parser/LexicFormula.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer ptformula__create_buffer
#define yy_delete_buffer ptformula__delete_buffer
#define yy_flex_debug ptformula__flex_debug
#define yy_init_buffer ptformula__init_buffer
#define yy_flush_buffer ptformula__flush_buffer
#define yy_load_buffer_state ptformula__load_buffer_state
#define yy_switch_to_buffer ptformula__switch_to_buffer
#define yyin ptformula_in
#define yyleng ptformula_leng
#define yylex ptformula_lex
#define yylineno ptformula_lineno
#define yyout ptformula_out
#define yyrestart ptformula_restart
#define yytext ptformula_text
#define yywrap ptformula_wrap
#define yyalloc ptformula_alloc
#define yyrealloc ptformula_realloc
#define yyfree ptformula_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE ptformula_restart(ptformula_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t ptformula_leng;

extern FILE *ptformula_in, *ptformula_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE ptformula_lex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-ptformula_lineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < ptformula_leng; ++yyl )\
                    if ( ptformula_text[yyl] == '\n' )\
                        --ptformula_lineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up ptformula_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up ptformula_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via ptformula_restart()), so that the user can continue scanning by
	 * just pointing ptformula_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when ptformula_text is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t ptformula_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow ptformula_wrap()'s to do buffer switches
 * instead of setting up a fresh ptformula_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void ptformula_restart (FILE *input_file  );
void ptformula__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE ptformula__create_buffer (FILE *file,int size  );
void ptformula__delete_buffer (YY_BUFFER_STATE b  );
void ptformula__flush_buffer (YY_BUFFER_STATE b  );
void ptformula_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void ptformula_pop_buffer_state (void );

static void ptformula_ensure_buffer_stack (void );
static void ptformula__load_buffer_state (void );
static void ptformula__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER ptformula__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE ptformula__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE ptformula__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE ptformula__scan_bytes (yyconst char *bytes,yy_size_t len  );

void *ptformula_alloc (yy_size_t  );
void *ptformula_realloc (void *,yy_size_t  );
void ptformula_free (void *  );

#define yy_new_buffer ptformula__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        ptformula_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ptformula__create_buffer(ptformula_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        ptformula_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ptformula__create_buffer(ptformula_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define ptformula_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *ptformula_in = (FILE *) 0, *ptformula_out = (FILE *) 0;

typedef int yy_state_type;

extern int ptformula_lineno;

int ptformula_lineno = 1;

extern char *ptformula_text;
#define yytext_ptr ptformula_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up ptformula_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	ptformula_leng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 50
#define YY_END_OF_BUFFER 51
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[310] =
    {   0,
        0,    0,    0,    0,   51,   48,   46,   45,   45,   48,
       41,   37,   38,   36,   34,   49,   35,   48,   47,   28,
       40,   33,   39,   27,   48,   27,   27,   27,   48,   48,
       48,   27,   48,   27,   27,   48,   49,    3,    3,    5,
        5,    3,    3,    3,    3,    4,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,   48,
       30,   47,   32,    1,   48,   43,   31,   42,   27,   48,
       48,   48,   48,   27,   27,   48,   48,   48,   48,   48,
       48,   13,   27,   48,   48,   48,   44,    0,    6,    3,

        3,    3,    2,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
       29,   48,   48,   11,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   12,   27,   48,   48,   48,   14,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   15,   48,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,   48,   48,   48,   48,   48,   16,   48,   48,
       48,   48,   48,   48,   48,   48,   21,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,   48,   19,   48,   48,   18,   48,   48,   48,
       48,   48,   48,   48,   48,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,   17,   48,
       48,   48,   10,   48,    8,   48,   48,   48,   23,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        9,   48,    7,   48,   48,   48,   48,    3,    3,    3,
        3,    3,    3,    3,   48,   48,   25,   22,   24,    3,

        3,    3,    3,    3,   20,   26,    3,    3,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    1,    6,    1,    1,    1,    1,    7,
        8,    9,   10,   11,   12,    1,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   11,   15,   16,
       17,   18,    1,    1,   19,   20,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   31,   32,   33,
        1,   34,   35,   36,   37,   38,   39,   40,   41,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       42,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   43,    1,   44,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[45] =
    {   0,
        1,    2,    3,    3,    1,    1,    2,    2,    4,    1,
        2,    1,    1,    1,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    2
    } ;

static yyconst flex_int16_t yy_base[315] =
    {   0,
        0,    0,   44,    0,  538,    0,  539,  539,  539,  520,
        0,  539,  539,    0,    0,  539,   75,  527,  521,  539,
       78,    0,  517,   78,  510,   79,   94,   63,   68,   68,
      498,   91,  497,   75,   98,  488,  485,  129,    0,  539,
      539,  172,  511,    0,    0,  514,  509,    0,  125,  107,
      118,    0,  116,  508,  507,  200,   88,  116,  130,  117,
      133,  135,  134,  146,  136,  147,  153,  124,  146,    0,
        0,  509,    0,    0,  504,    0,    0,    0,  157,  162,
      499,  501,  496,  163,  164,  484,  483,  483,  133,  475,
      478,    0,  178,  476,  476,  477,    0,  466,  465,  491,

        0,  490,    0,  185,  489,  186,  488,  487,  486,  169,
      189,  188,  194,  191,  210,  191,  204,  210,  209,  218,
      213,  215,  485,  217,  230,  216,  232,  484,  241,  245,
        0,  467,  480,    0,  476,  466,  477,  460,  471,  463,
      460,  455,  471,  453,    0,  234,  465,  464,  459,    0,
      468,  240,  241,  467,  242,  244,  251,  245,  254,  252,
      255,  257,  259,  262,  466,  263,  273,  274,  278,  465,
      462,  439,  450,  442,  441,  453,  456,  437,  438,  445,
      437,  435,  443,  449,    0,  438,  264,  269,  271,  282,
      284,  285,  287,  286,  290,  292,  294,  295,  296,  297,

      449,  298,  429,  429,  431,  425,  435,    0,  440,  430,
      423,  438,  429,  419,  435,  418,    0,  300,  304,  309,
      307,  312,  435,  314,  316,  315,  318,  325,  323,  329,
      326,  434,  424,    0,  428,  429,    0,  418,  427,  418,
      415,  424,  423,  421,  417,  330,  422,  332,  338,  421,
      334,  341,  337,  345,  348,  349,  352,  353,    0,  409,
      407,  412,    0,  414,    0,  402,  396,  401,    0,  407,
      354,  356,  358,  403,  360,  399,  361,  362,  366,  398,
        0,  383,    0,  382,  374,  386,  385,  390,  367,  387,
      370,  369,  371,  374,  362,  379,    0,    0,    0,  372,

      383,  384,  376,  373,    0,    0,  195,  148,  539,  413,
      417,  421,  425,  427
    } ;

static yyconst flex_int16_t yy_def[315] =
    {   0,
      309,    1,  309,    3,  309,  310,  309,  309,  309,  310,
      310,  309,  309,  310,  310,  309,  310,  310,  310,  309,
      310,  310,  310,  310,  310,   24,   24,   24,  310,  310,
      310,   24,  310,   24,   24,  310,  311,  312,  313,  309,
      309,  312,   42,  313,  313,  310,   42,  313,   42,   42,
       42,  313,   42,   42,   42,   42,   42,   56,   56,   56,
       42,   42,   42,   56,   42,   56,   56,   42,  314,  310,
      310,  310,  310,  310,  310,  310,  310,  310,   24,  310,
      310,  310,  310,   24,   24,  310,  310,  310,  310,  310,
      310,  310,   24,  310,  310,  310,  310,  311,  311,   42,

      313,   42,  310,   42,   42,   42,   42,   42,   42,   56,
       42,   42,   42,   42,   56,   56,   42,   42,   42,   42,
       42,   42,   42,   56,   42,   42,   42,   42,  314,  314,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,   24,  310,  310,  310,  310,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   56,   42,   42,   42,   42,
      310,  310,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,

       42,   42,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  310,  310,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,  310,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   42,  310,  310,
      310,  310,  310,  310,  310,  310,  310,  310,  310,   42,
       42,   42,   42,   42,   42,   42,   42,   42,   42,   42,
      310,  310,  310,  310,  310,  310,  310,   42,   42,   42,
       42,   42,   42,   42,  310,  310,  310,  310,  310,   42,

       42,   42,   42,   42,  310,  310,   42,   42,    0,  309,
      309,  309,  309,  309
    } ;

static yyconst flex_int16_t yy_nxt[584] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,    6,
        6,   25,   26,   27,   28,    6,   29,    6,    6,    6,
       30,   31,    6,   32,    6,   33,   34,    6,    6,   35,
        6,   36,   37,   16,   38,   39,   40,   41,   42,   43,
       44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,   38,   38,   57,   58,   59,   60,   38,
       61,   38,   38,   38,   62,   63,   38,   64,   38,   65,
       66,   38,   38,   67,   38,   68,   69,   48,   72,   75,
       90,   70,   73,   70,   76,   77,   79,   88,   89,   91,

       79,   79,   79,   70,  100,   95,   80,   70,   81,   70,
      113,   79,   85,   93,   79,   74,   83,   79,   84,   70,
       86,   70,   70,  100,   70,   87,   70,  106,   70,   96,
      101,  104,  107,  108,  100,  101,  101,   70,  104,  101,
      100,  100,  105,  101,  100,  100,  100,  100,  116,  100,
      100,  100,  100,  114,   98,  115,  117,  121,  100,  142,
      100,  118,  119,  120,  100,  128,  122,  123,  124,  125,
      143,  101,  101,  101,  100,  100,  100,  126,  101,  101,
       70,  100,  101,  100,  127,   70,  101,   70,  102,  130,
      132,   70,  138,   70,   70,  137,  146,  100,  104,  100,

      133,  100,  100,  151,  100,  100,  147,  100,   70,  154,
      100,  100,  155,  156,  101,  101,  100,  152,  110,  158,
      100,  100,  110,  110,  110,  100,  100,  153,  111,  100,
      112,  100,  100,  110,  100,  166,  110,  159,  100,  110,
      100,  161,  157,  160,  162,  167,  100,  100,  100,   98,
      165,  169,  164,   98,  183,  163,  100,  100,  100,  188,
      100,  100,   70,  189,   70,  170,  168,  100,  100,  191,
      100,  100,  187,  100,  190,  100,  193,  197,  100,  192,
      100,  194,  218,  199,  130,  100,  195,  100,  130,  100,
      100,  100,  196,  100,  100,  200,  201,  198,  100,  220,

      100,  100,  100,  100,  202,  224,  100,  223,  100,  219,
      100,  100,  100,  100,  100,  231,  100,  221,  227,  222,
      100,  230,  225,  100,  226,  100,  232,  228,  100,  229,
      100,  100,  100,  251,  100,  246,  254,  250,  247,  100,
      248,  100,  100,  249,  252,  100,  100,  257,  100,  253,
      100,  255,  271,  100,  100,  270,  272,  100,  256,  274,
      258,  100,  273,  275,  100,  100,  277,  278,  100,  100,
      100,  279,  100,  276,  100,  280,  100,  100,  100,  291,
      290,  288,  100,  100,  289,  100,  100,  100,  100,  100,
      100,  292,  100,  303,  294,  300,  304,  293,  301,  100,

      100,  306,  305,  100,  302,  308,  100,  299,  298,  297,
      296,  295,  307,   70,  100,  100,   70,   98,   98,  100,
       98,  100,  100,  100,  100,  101,  101,  129,  129,  287,
      129,  286,  285,  284,  283,  282,  281,  100,  100,  269,
      268,  267,  266,  265,  264,  263,  262,  261,  260,  259,
      100,  100,  245,  244,  243,  242,  241,  240,  239,  238,
      237,  236,  235,  234,  233,  100,  217,  216,  215,  214,
      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  100,  100,  100,  100,  186,  185,  184,  182,  181,
      180,  179,  178,  177,  176,  175,  174,  173,  172,  171,

      100,  100,  100,  100,  100,  100,  100,  100,   99,   99,
      150,  149,  148,  145,  144,  141,  140,  139,  136,  135,
      134,  131,   72,  109,  100,  100,  103,  100,   99,   97,
       94,   92,   82,   78,   72,   74,   71,  309,    5,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309
    } ;

static yyconst flex_int16_t yy_chk[584] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,   17,   21,
       30,   28,   17,   28,   21,   21,   24,   29,   29,   30,

       24,   24,   24,   34,   57,   34,   24,   26,   24,   26,
       57,   24,   27,   32,   24,   50,   26,   24,   26,   32,
       27,   32,   27,   50,   27,   27,   35,   53,   35,   35,
       38,   51,   53,   53,   51,   38,   38,   38,   49,   38,
       68,   49,   49,   38,   58,   60,   58,   60,   59,   61,
       63,   62,   65,   58,   69,   58,   59,   62,   59,   89,
       59,   59,   61,   61,  308,   68,   62,   63,   64,   65,
       89,   38,   38,   42,   64,   66,   64,   66,   42,   42,
       42,   67,   42,   67,   67,   79,   42,   79,   42,   69,
       80,   84,   85,   84,   85,   84,   93,  110,  104,  110,

       80,  104,  106,  106,  112,  111,   93,  114,   93,  112,
      113,  307,  113,  114,   42,   42,   56,  111,   56,  116,
      117,  116,   56,   56,   56,  119,  118,  111,   56,  121,
       56,  122,  126,   56,  120,  124,   56,  117,  115,   56,
      115,  119,  115,  118,  120,  124,  125,  124,  127,  129,
      122,  126,  121,  130,  146,  120,  152,  153,  155,  153,
      156,  158,  146,  155,  146,  127,  125,  157,  160,  157,
      159,  161,  152,  162,  156,  163,  159,  163,  164,  158,
      187,  160,  187,  166,  129,  188,  161,  189,  130,  167,
      168,  166,  162,  166,  169,  167,  168,  164,  190,  189,

      191,  192,  194,  193,  169,  193,  195,  192,  196,  188,
      197,  198,  199,  200,  202,  200,  218,  190,  196,  191,
      219,  199,  194,  221,  195,  220,  202,  197,  222,  198,
      224,  226,  225,  224,  227,  218,  227,  222,  219,  229,
      220,  228,  231,  221,  225,  230,  246,  230,  248,  226,
      251,  228,  248,  253,  249,  246,  249,  252,  229,  252,
      231,  254,  251,  253,  255,  256,  255,  256,  257,  258,
      271,  257,  272,  254,  273,  258,  275,  277,  278,  275,
      273,  271,  279,  289,  272,  292,  291,  293,  300,  304,
      294,  277,  303,  293,  279,  289,  294,  278,  291,  301,

      302,  296,  295,  290,  292,  301,  288,  287,  286,  285,
      284,  282,  300,  310,  280,  276,  310,  311,  311,  274,
      311,  312,  312,  270,  312,  313,  313,  314,  314,  268,
      314,  267,  266,  264,  262,  261,  260,  250,  247,  245,
      244,  243,  242,  241,  240,  239,  238,  236,  235,  233,
      232,  223,  216,  215,  214,  213,  212,  211,  210,  209,
      207,  206,  205,  204,  203,  201,  186,  184,  183,  182,
      181,  180,  179,  178,  177,  176,  175,  174,  173,  172,
      171,  170,  165,  154,  151,  149,  148,  147,  144,  143,
      142,  141,  140,  139,  138,  137,  136,  135,  133,  132,

      128,  123,  109,  108,  107,  105,  102,  100,   99,   98,
       96,   95,   94,   91,   90,   88,   87,   86,   83,   82,
       81,   75,   72,   55,   54,   47,   46,   43,   37,   36,
       33,   31,   25,   23,   19,   18,   10,    5,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[51] =
    {   0,
0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int ptformula__flex_debug;
int ptformula__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *ptformula_text;
#line 1 "Frontend/Parser/LexicFormula.ll"
/****************************************************************************
  This file is part of LoLA.

  LoLA is free software: you can redistribute it and/or modify it under the
  terms of the GNU Affero General Public License as published by the Free
  Software Foundation, either version 3 of the License, or (at your option)
  any later version.

  LoLA is distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
  FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for
  more details.

  You should have received a copy of the GNU Affero General Public License
  along with LoLA. If not, see <http://www.gnu.org/licenses/>.
****************************************************************************/
/*!
\file
\brief lexic for formulas
\author Karsten
\status approved 25.01.2012
\ingroup g_frontend

\todo Herausfinden, ob es Probleme bei zu langen Kommentaren/Bezeichnern gibt.
Idee: Maximallänge angeben.
\todo Präfix hinzufügen?
*/
/* ptformula_lineno: we want line numbering
   nounput: we don't need yyunput()
   noyywrap: we don't support multiple formula files */
#line 40 "Frontend/Parser/LexicFormula.ll"
#include <Frontend/Parser/ast-system-k.h>       // for kc namespace
#include <Frontend/Parser/ast-system-yystype.h> // for YYSTYPE
#include <Frontend/Parser/ParserFormula.hh>

extern void ptformula_error(char const* mess);
unsigned int ptformula_colno = 1;

/*!
\brief This macro is executed prior to the matched rule's action.

We use this macro to set set #ptformula_lloc to the positions of
#ptformula_text. It further manages the current column number #ptformula_colno.
See Flex's manual http://flex.sourceforge.net/manual/Misc-Macros.html for more
information on the macro.
*/
#define YY_USER_ACTION \
  ptformula_lloc.first_line = ptformula_lloc.last_line = ptformula_lineno; \
  ptformula_lloc.first_column = ptformula_colno; \
  ptformula_lloc.last_column = ptformula_colno+ptformula_leng-1; \
  ptformula_colno += ptformula_leng;

#line 774 "Frontend/Parser/LexicFormula.cc"

#define INITIAL 0
#define IN_COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int ptformula_lex_destroy (void );

int ptformula_get_debug (void );

void ptformula_set_debug (int debug_flag  );

YY_EXTRA_TYPE ptformula_get_extra (void );

void ptformula_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *ptformula_get_in (void );

void ptformula_set_in  (FILE * in_str  );

FILE *ptformula_get_out (void );

void ptformula_set_out  (FILE * out_str  );

yy_size_t ptformula_get_leng (void );

char *ptformula_get_text (void );

int ptformula_get_lineno (void );

void ptformula_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int ptformula_wrap (void );
#else
extern int ptformula_wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( ptformula_text, ptformula_leng, 1, ptformula_out )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( ptformula_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( ptformula_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, ptformula_in))==0 && ferror(ptformula_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(ptformula_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int ptformula_lex (void);

#define YY_DECL int ptformula_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after ptformula_text and ptformula_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 64 "Frontend/Parser/LexicFormula.ll"


 /* from http://flex.sourceforge.net/manual/How-can-I-match-C_002dstyle-comments_003f.html */
#line 959 "Frontend/Parser/LexicFormula.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! ptformula_in )
			ptformula_in = stdin;

		if ( ! ptformula_out )
			ptformula_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			ptformula_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				ptformula__create_buffer(ptformula_in,YY_BUF_SIZE );
		}

		ptformula__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of ptformula_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 310 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 539 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < ptformula_leng; ++yyl )
				if ( ptformula_text[yyl] == '\n' )
					   
    ptformula_lineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 67 "Frontend/Parser/LexicFormula.ll"
{ BEGIN(IN_COMMENT); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 68 "Frontend/Parser/LexicFormula.ll"
{ BEGIN(INITIAL); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 69 "Frontend/Parser/LexicFormula.ll"
{ /* comments */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 70 "Frontend/Parser/LexicFormula.ll"
{ /* comments */ }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 71 "Frontend/Parser/LexicFormula.ll"
{ /* comments */ }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 72 "Frontend/Parser/LexicFormula.ll"
{ /* comments */ }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 74 "Frontend/Parser/LexicFormula.ll"
{ return _FIREABLE_; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 75 "Frontend/Parser/LexicFormula.ll"
{ return _INITIAL_; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 76 "Frontend/Parser/LexicFormula.ll"
{ return _DEADLOCK_; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 78 "Frontend/Parser/LexicFormula.ll"
{ return _FORMULA_; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 79 "Frontend/Parser/LexicFormula.ll"
{ return _AND_; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 80 "Frontend/Parser/LexicFormula.ll"
{ return _NOT_; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 81 "Frontend/Parser/LexicFormula.ll"
{ return _OR_; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 82 "Frontend/Parser/LexicFormula.ll"
{ return _XOR_; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 83 "Frontend/Parser/LexicFormula.ll"
{ return _TRUE_; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 84 "Frontend/Parser/LexicFormula.ll"
{ return _FALSE_; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 86 "Frontend/Parser/LexicFormula.ll"
{ return _ALLPATH_; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 87 "Frontend/Parser/LexicFormula.ll"
{ return _EXPATH_; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 89 "Frontend/Parser/LexicFormula.ll"
{ return _ALWAYS_; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 90 "Frontend/Parser/LexicFormula.ll"
{ return _EVENTUALLY_; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 91 "Frontend/Parser/LexicFormula.ll"
{ return _UNTIL_; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 92 "Frontend/Parser/LexicFormula.ll"
{ return _NEXTSTATE_; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 93 "Frontend/Parser/LexicFormula.ll"
{ return _RELEASE_; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 95 "Frontend/Parser/LexicFormula.ll"
{ return _REACHABLE_; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 96 "Frontend/Parser/LexicFormula.ll"
{ return _INVARIANT_; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 97 "Frontend/Parser/LexicFormula.ll"
{ return _IMPOSSIBLE_; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 99 "Frontend/Parser/LexicFormula.ll"
{ ptformula_lval.yt_casestring = kc::mkcasestring(ptformula_text); return _CTLOPERATOR_; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 101 "Frontend/Parser/LexicFormula.ll"
{ return _semicolon_; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 102 "Frontend/Parser/LexicFormula.ll"
{ return _iff_; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 103 "Frontend/Parser/LexicFormula.ll"
{ return _notequal_; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 104 "Frontend/Parser/LexicFormula.ll"
{ return _notequal_; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 105 "Frontend/Parser/LexicFormula.ll"
{ return _implies_; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 106 "Frontend/Parser/LexicFormula.ll"
{ return _equals_; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 107 "Frontend/Parser/LexicFormula.ll"
{ return _plus_; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 108 "Frontend/Parser/LexicFormula.ll"
{ return _minus_; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 109 "Frontend/Parser/LexicFormula.ll"
{ return _times_; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 110 "Frontend/Parser/LexicFormula.ll"
{ return _leftparenthesis_; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 111 "Frontend/Parser/LexicFormula.ll"
{ return _rightparenthesis_; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 112 "Frontend/Parser/LexicFormula.ll"
{ return _greaterthan_; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 113 "Frontend/Parser/LexicFormula.ll"
{ return _lessthan_; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 114 "Frontend/Parser/LexicFormula.ll"
{ return _notequal_; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 115 "Frontend/Parser/LexicFormula.ll"
{ return _greaterorequal_; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 116 "Frontend/Parser/LexicFormula.ll"
{ return _lessorequal_; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 118 "Frontend/Parser/LexicFormula.ll"
{ return _omega_; }
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 120 "Frontend/Parser/LexicFormula.ll"
{ ptformula_colno = 1; /* whitespace */ }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 121 "Frontend/Parser/LexicFormula.ll"
{  /* whitespace */ }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 123 "Frontend/Parser/LexicFormula.ll"
{ ptformula_lval.yt_integer = kc::mkinteger(atoi(ptformula_text)); return NUMBER; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 124 "Frontend/Parser/LexicFormula.ll"
{ ptformula_lval.yt_casestring = kc::mkcasestring(ptformula_text); return IDENTIFIER; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 126 "Frontend/Parser/LexicFormula.ll"
{ ptformula_error("lexical error"); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 127 "Frontend/Parser/LexicFormula.ll"
ECHO;
	YY_BREAK
#line 1304 "Frontend/Parser/LexicFormula.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IN_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed ptformula_in at a new source and called
			 * ptformula_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = ptformula_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( ptformula_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * ptformula_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of ptformula_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					ptformula_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			ptformula_restart(ptformula_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) ptformula_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 310 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 310 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 309);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					ptformula_restart(ptformula_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( ptformula_wrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve ptformula_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    ptformula_lineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void ptformula_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        ptformula_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            ptformula__create_buffer(ptformula_in,YY_BUF_SIZE );
	}

	ptformula__init_buffer(YY_CURRENT_BUFFER,input_file );
	ptformula__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void ptformula__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		ptformula_pop_buffer_state();
	 *		ptformula_push_buffer_state(new_buffer);
     */
	ptformula_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	ptformula__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (ptformula_wrap()) processing, but the only time this flag
	 * is looked at is after ptformula_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void ptformula__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	ptformula_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE ptformula__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) ptformula_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ptformula__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) ptformula_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in ptformula__create_buffer()" );

	b->yy_is_our_buffer = 1;

	ptformula__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with ptformula__create_buffer()
 * 
 */
    void ptformula__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		ptformula_free((void *) b->yy_ch_buf  );

	ptformula_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a ptformula_restart() or at EOF.
 */
    static void ptformula__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	ptformula__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then ptformula__init_buffer was _probably_
     * called from ptformula_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void ptformula__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		ptformula__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void ptformula_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	ptformula_ensure_buffer_stack();

	/* This block is copied from ptformula__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from ptformula__switch_to_buffer. */
	ptformula__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void ptformula_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	ptformula__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		ptformula__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void ptformula_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)ptformula_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ptformula_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)ptformula_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ptformula_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE ptformula__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) ptformula_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ptformula__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	ptformula__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to ptformula_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       ptformula__scan_bytes() instead.
 */
YY_BUFFER_STATE ptformula__scan_string (yyconst char * yystr )
{
    
	return ptformula__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to ptformula_lex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE ptformula__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) ptformula_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in ptformula__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = ptformula__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in ptformula__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up ptformula_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		ptformula_text[ptformula_leng] = (yy_hold_char); \
		(yy_c_buf_p) = ptformula_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		ptformula_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int ptformula_get_lineno  (void)
{
        
    return ptformula_lineno;
}

/** Get the input stream.
 * 
 */
FILE *ptformula_get_in  (void)
{
        return ptformula_in;
}

/** Get the output stream.
 * 
 */
FILE *ptformula_get_out  (void)
{
        return ptformula_out;
}

/** Get the length of the current token.
 * 
 */
yy_size_t ptformula_get_leng  (void)
{
        return ptformula_leng;
}

/** Get the current token.
 * 
 */

char *ptformula_get_text  (void)
{
        return ptformula_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void ptformula_set_lineno (int  line_number )
{
    
    ptformula_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see ptformula__switch_to_buffer
 */
void ptformula_set_in (FILE *  in_str )
{
        ptformula_in = in_str ;
}

void ptformula_set_out (FILE *  out_str )
{
        ptformula_out = out_str ;
}

int ptformula_get_debug  (void)
{
        return ptformula__flex_debug;
}

void ptformula_set_debug (int  bdebug )
{
        ptformula__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from ptformula_lex_destroy(), so don't allocate here.
     */

    /* We do not touch ptformula_lineno unless the option is enabled. */
    ptformula_lineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    ptformula_in = stdin;
    ptformula_out = stdout;
#else
    ptformula_in = (FILE *) 0;
    ptformula_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * ptformula_lex_init()
     */
    return 0;
}

/* ptformula_lex_destroy is for both reentrant and non-reentrant scanners. */
int ptformula_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		ptformula__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		ptformula_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	ptformula_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * ptformula_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *ptformula_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *ptformula_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void ptformula_free (void * ptr )
{
	free( (char *) ptr );	/* see ptformula_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 127 "Frontend/Parser/LexicFormula.ll"
